# Generated by Django 6.0.1 on 2026-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
