# Generated by Django 6.0.1 on 2026-02-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0006_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence & ML')], max_length=10)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.student')),
            ],
        ),
    ]
