# Generated by Django 6.0.1 on 2026-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0007_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
