# Generated by Django 6.0.1 on 2026-02-19 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0011_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.subject'),
        ),
    ]
