# Generated by Django 6.0.1 on 2026-02-19 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0012_document_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence & ML')], max_length=10)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.college')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.subject')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'year', 'subject', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.student')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ssmsapp.attendancesession')),
            ],
            options={
                'unique_together': {('attendance_session', 'student')},
            },
        ),
    ]
