# Generated by Django 6.0.1 on 2026-02-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0015_question_created_at_question_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('answers_json', models.JSONField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('dys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.departmentyearsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssmsapp.student')),
            ],
        ),
    ]
