# Generated by Django 6.0.1 on 2026-02-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0016_studentexamattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexamattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together={('student', 'dys')},
        ),
    ]
