# Generated by Django 6.0.1 on 2026-02-21 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0019_auto_20260221_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='paper',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attempts',
                to='ssmsapp.questionpaper',
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE ssmsapp_studentexamattempt
                SET paper_id = (
                    SELECT q.id
                    FROM ssmsapp_questionpaper q
                    WHERE q.dept_year_subject_id = ssmsapp_studentexamattempt.dys_id
                      AND q.started_at IS NOT NULL
                      AND q.started_at <= ssmsapp_studentexamattempt.attempted_at
                    ORDER BY q.started_at DESC
                    LIMIT 1
                )
                WHERE paper_id IS NULL
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together={('student', 'paper')},
        ),
    ]
