# Generated by Django 6.0.1 on 2026-02-21 21:44

import ssmsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssmsapp', '0020_studentexamattempt_paper_and_unique_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=300, upload_to=ssmsapp.models.document_upload_path),
        ),
    ]
